import java.util.Random;

public class ComputerPlayer extends Player{

    private Random rand;

    public ComputerPlayer(char counter) {
        super(counter);
        rand = new Random();
    }

    public int getMove() {
        //The computer player's move is generated by a random number generator.
        return (rand.nextInt(7)+1);
    }
}
